version: "3.9"

services:
  # web:
  #   build:
  #     dockerfile: ./apps/web/Dockerfile
  #     target: development
  #     context: .
  #   restart: always
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3010:4200"
  #   command: bash -c 'npm run serve:web'
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      target: development
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
      - cache
    ports:
      - "${PORT}:${PORT}"
      # Prisma Studio port
      - 5555:5555
    networks:
      - shared-network
    command: bash -c 'npx prisma generate && npm run serve:backend'

  db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network

  cache:
    image: redis:7.0.8-alpine
    env_file:
      - ./.env
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - rediscache:/data
    networks:
      - shared-network

volumes:
  pgdata:
  rediscache:

networks:
  shared-network:
