version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      target: development
    restart: always
    env_file:
      - ./.env
      - ./apps/backend/.env.local
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
      - cache
    ports:
      - "${PORT}:${PORT}"
      # Prisma Studio port
      - 5555:5555
    networks:
      - shared-network
    command: bash -c 'npm run db:generate && npm run db:push && npm run serve:backend'

  db:
    image: postgres:15.2-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - shared-network

  cache:
    image: redis:7.0.8-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - rediscache:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - shared-network

volumes:
  pgdata:
  rediscache:

networks:
  shared-network:
